// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

type Bungalow struct {
	ID       int32 `db:"id" json:"id"`
	Capacity int32 `db:"capacity" json:"capacity"`
}

type BungalowsUser struct {
	ID       int32  `db:"id" json:"id"`
	Capacity int32  `db:"capacity" json:"capacity"`
	Users    []User `db:"users" json:"users"`
}

type RefreshToken struct {
	ID        string           `db:"id" json:"id"`
	FirstName string           `db:"first_name" json:"first_name"`
	LastName  string           `db:"last_name" json:"last_name"`
	IsRevoked pgtype.Bool      `db:"is_revoked" json:"is_revoked"`
	Token     string           `db:"token" json:"token"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int32         `db:"id" json:"id"`
	FirstName    string        `db:"first_name" json:"first_name"`
	LastName     string        `db:"last_name" json:"last_name"`
	HashPassword string        `db:"hash_password" json:"hash_password"`
	IsActivated  bool          `db:"is_activated" json:"is_activated"`
	HasPaid      bool          `db:"has_paid" json:"has_paid"`
	IsAdmin      bool          `db:"is_admin" json:"is_admin"`
	BungalowID   sql.NullInt32 `db:"bungalow_id" json:"bungalow_id"`
}
